apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: jet-form
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jet-form
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: jet-form
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jet-form
      spec:
        containers:
        - env:
          - name: JIRA_TOKEN
            valueFrom:
              secretKeyRef:
                key: token
                name: jira-token
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: jet-form
            #          livenessProbe:
            #            httpGet:
            #              path: /
            #              port: 8000
            #            initialDelaySeconds: 5
            #            timeoutSeconds: 10
          resources:
            limits:
              cpu: 750m
              memory: 400Mi
            requests:
              cpu: 200m
              memory: 200Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
          #        imagePullSecrets:
          #        - name: quay-cloudservices-pull
          #        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
parameters:
- description: Image name
  name: IMAGE
  value: quay.io/bturner/jet-form
- description: Image tag
  name: IMAGE_TAG
  value: "latest"
  required: true
